config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :devices
  resources :lots
  resources :sites
  resources :alerts

  root to:'root#home'
  match ':controller(/:id(/:action(.:format)))', :via => :all

end

app/models/device.rb
class Device < ActiveRecord::Base

  has_many :lots, :dependent => :destroy
  #validate device uniqueness
  validates :name, uniqueness: true
  
  #validate the necessary blank
  validates :name, presence: true


  #validate the site difference parameter must exists
  validates :site_difference_detect_window, presence: true, :unless => lambda { self.site_difference_detect_enable == false }
  validates :site_difference_detect_threshold, presence: true, :unless => lambda { self.site_difference_detect_enable == false }

  #validate the continuously failure parameter must exist
  validates :continuously_failure_detect_threshold, presence: true, :unless => lambda { self.continuously_failure_detect_enable == false }

  #validate the time variance parameter must exist
  validates :time_variance_detect_window_small, presence: true, :unless => lambda { self.time_variance_detect_enable == false }
  validates :time_variance_detect_window_large, presence: true, :unless => lambda { self.time_variance_detect_enable == false }
  validates :time_variance_detect_threshold, presence: true, :unless => lambda { self.time_variance_detect_enable == false }

  #validate the different tester variance parameters must exist
  validates :different_tester_variance_detect_window, presence: true, :unless => lambda { self.different_tester_variance_detect_enable == false }
  validates :different_tester_variance_detect_threshold, presence: true, :unless => lambda { self.different_tester_variance_detect_enable == false }

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  #before_action :set_device, :only => [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
    @devices = Device.page(params[:page]).per(10)
  end

  def new
    @device = Device.new
    @page_title = "new device"
  end

  def create
    @device = Device.new(device_params)
    if @device.save
      redirect_to :action => :index
      flash[:notice] = "detection rules were succesfully created"
    else
      render :action => :new
    end
  end

  def show
    @device = Device.find(params[:id])
    @page_title = @device.name
  end

  def edit
    @device = Device.find(params[:id])
    @page_title = "edit " + @device.name
  end

  def update
    @device = Device.find(params[:id])
    if @device.update(device_params)
      redirect_to :action => :show, :id => @device
      flash[:notice] = "detection rules were succesfully updated"
    else
      render :action => :edit
    end
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy
    flash[:alert] = "detection rules were succesfully deleted"

    redirect_to :action => :index
  end

  private

  def device_params
    params.require(:device).permit(
        :name,
        :site_difference_detect_enable,
        :site_difference_detect_window,
        :site_difference_detect_threshold,
        :continuously_failure_detect_enable,
        :continuously_failure_detect_threshold,
        :time_variance_detect_enable,
        :time_variance_detect_window_small,
        :time_variance_detect_window_large,
        :time_variance_detect_threshold,
        :different_tester_variance_detect_enable,
        :different_tester_variance_detect_window,
        :different_tester_variance_detect_threshold
    )
  end

  def set_device
    @device = Device.find(params[:id])
  end

end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= f.label :name, "Device Name" %>
<%= f.text_field :name %><br>

<%= f.label :site_difference_detect_enable do %>
	<%= f.check_box :site_difference_detect_enable %>
	Enable The Site Difference Detection.
<% end %>
<ul>
	<li><%= f.label "Window Size" %><%= f.number_field :site_difference_detect_window, :class => 'text_field', min: 0, step: 1 %></li>
	<li><%= f.label "Yield Difference Threshold" %>
		<%= f.number_field :site_difference_detect_threshold, :class => 'text_field', min: 0.0, max: 100.0, step: 0.01 %></li>
</ul>

<%= f.label :continuously_failure_detect_enable do %>
	<%= f.check_box :continuously_failure_detect_enable %>
	Enable The Continuously Failure Detection.
<% end %>
<ul>
	<li><%= f.label "Continuously Fail Pieces Threshold" %><%= f.number_field :continuously_failure_detect_threshold, min: 0, step: 1 %></li>
</ul>

<%= f.label :time_variance_detect_enable do %>
	<%= f.check_box :time_variance_detect_enable  %>
	Enable The Time Variance Detection.
<% end %>
<ul>
	<li><%= f.label "Window Size(Large)" %>
		<%= f.number_field :time_variance_detect_window_large, min: 0, step: 1 %></li>
	<li><%= f.label "Window Size(Small)" %>
		<%= f.number_field :time_variance_detect_window_small, min: 0, step: 1 %></li>
	<li><%= f.label :time_variance_detect_threshold, "Yield Difference Threshold" %>
		<%= f.number_field :time_variance_detect_threshold, :class => 'text_field', min: 0.0, max: 100.0, step: 0.01 %></li>
</ul>


<%= f.label :different_tester_variance_detect_enable do %>
	<%= f.check_box :different_tester_variance_detect_enable  %>
	Enable The Different Testers Variance Detection.
<% end %>
<ul>
	<li><%= f.label "Window Size" %>
		<%= f.number_field :different_tester_variance_detect_window, min: 0, step: 1 %></li>
	<li><%= f.label :different_tester_variance_detect_threshold, "Yield Difference Threshold" %>
		<%= f.number_field :different_tester_variance_detect_threshold, :class => 'text_field', min: 0.0, max: 100.0, step: 0.01 %></li>
</ul>

<% if @device.errors.any? %>
	<ul>
		<% @device.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

app/views/devices/edit.html.erb
<%= form_for @device, :url => device_path(@device) do |f| %>
	<div class="page-header">
		<h1>Detection Rules <small>Edit</small></h1>
	</div>
	<%= render :partial => 'form', :locals => { :f => f } %>

	<br>
	<%= f.submit "Update" %>
	<%= link_to 'back to device index', :controller => 'devices', :action => 'index' %>

<% end %>

app/views/devices/index.html.erb
<h1>Devices Index</h1>
<%= paginate @devices %>
<ul class="list-group">
	<% @devices.each do |device| %>
		<li class="list-group-item">
			<%= device.name %>
			<%= link_to("Show", device_path(device), class: "btn btn-default btn-xs") %>
			<%= link_to("Edit", edit_device_path(device), class: "btn btn-default btn-xs")%>
			<%= link_to("Delete", device_path(device), class: "btn btn-default btn-xs", :method => :delete, data: {confirm: "Are you sure?"} ) %>
		</li>
	<% end %>
</ul>
<%= link_to 'New Device', :controller => 'devices', :action => 'new' %>

app/views/devices/new.html.erb
<%= form_for @device, :url => devices_path do |f| %>

	<div class="page-header">
		<h1>Detection Rules <small>New</small></h1>
	</div>
	<%= render :partial => 'form', :locals => { :f => f } %>

	<br>
	<%= f.submit "Submit" %>
	<%= link_to 'back to device index', :controller => 'devices', :action => 'index' %>

<% end %>

app/views/devices/show.html.erb
<div class="page-header">
	<h1>Detection Rules <small><%= @device.name %></small></h1>
</div>

Device Name: <%= @device.name %><br>

<div>Enable The Site Difference Detection:
  <% if(@device.site_difference_detect_enable == true)  %>
		Yes<br>
		<ul>
			<li>Window Size: <%= @device.site_difference_detect_window %></li>
			<li>Yield Difference Threshold: <%= @device.site_difference_detect_threshold %></li>
		</ul>
	<% else %>
		No
	<% end %>
</div><!-- site difference div -->

<div>Enable The Continuously Failure Detection:
	<% if(@device.continuously_failure_detect_enable == true)  %>
		Yes<br>
		<ul>
			<li>Conimuously Failure Pieces Threshold: <%= @device.continuously_failure_detect_threshold %></li>
		</ul>
	<% else %>
		No
	<% end %>
</div><!-- continuously failure div -->

<div>Enable The Timing Variance Detection:
	<% if(@device.time_variance_detect_enable == true)  %>
		Yes<br>
		<ul>
			<li>Larger Window Size: <%= @device.time_variance_detect_window_large %></li>
			<li>Smaller Window Size: <%= @device.time_variance_detect_window_small %></li>
			<li>Yield Difference Threshold: <%= @device.time_variance_detect_threshold %></li>
		</ul>
	<% else %>
		No
	<% end %>
</div><!-- time variance div -->

<div>Enable The Different Tester Variance Detection:
<% if(@device.different_tester_variance_detect_enable == true)  %>
	Yes<br>
	<ul>
		<li>Window Size: <%= @device.different_tester_variance_detect_window %></li>
		<li>Yield Difference Threshold: <%= @device.different_tester_variance_detect_threshold %></li>
	</ul>
<% else %>
	No
<% end %>
</div><!-- different tester variance div -->


<p><%= link_to 'Back to index', :controller=>'devices', :action=>'index' %></p>