config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :devices
  resources :lots
  resources :sites
  resources :alerts

  root to:'root#home'
  match ':controller(/:id(/:action(.:format)))', :via => :all

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :lot
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController

  before_action :authenticate_user!, only: [:destroy]

  def index
    @alerts = Alert.page(params[:page]).per(50).order('id DESC')
  end

  def show
    @alert = Alert.find(params[:id])
  end

  def edit
    #@alert = Alert.find(params[:id])
  end

  def update
    #@alert = Alert.find(params[:id])
  end

  def destroy
    @alert = Alert.find(params[:id])
    #set lot detect flag to false
    a = @alert.lot
    if(@alert.alerts_kind == 1)
      a.site_difference_detected = false
    elsif(@alert.alerts_kind == 2)
      a.continuously_failure_detected = false
    elsif(@alert.alerts_kind == 3)
      a.time_variance_detected = false
    else
      Lot.find_each do |b|
        if(b.name == a.name)
          b.different_tester_variance_detected = false
          b.save
        end
      end
      a.different_tester_variance_detected = false
    end
    a.save

    @alert.destroy
    flash[:alert] = "Alert record was succesfully deleted"

    redirect_to :action => :index
  end
  private
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/index.html.erb
<div class="page-header">
	<h1>Alert List</h1>
</div>


<%= paginate @alerts %>
<div>
	<table class="table table-condensed table-bordered">
		<thead>
		<tr>
			<th>Lot</th>
			<th>Device</th>
			<th>Alert Type</th>
			<th>Alert Time</th>
			<th>fixed</th>
			<th>fixed time</th>
			<th>Detail</th>
		</tr>
		</thead>

		<tbody>
		<% @alerts.each do |alert| %>
			<% if(alert.fixed == true) %>
				<tr class="success">
			<% else %>
				<tr class="danger">
			<% end %>
				<td><%= "#{alert.lot.name}" %></td>
				<td><%= "#{alert.lot.device.name}" %></td>
				<% if(alert.alerts_kind == 1) %>
					<td><%= "SITE DIFFERENCE" %></td>
				<% elsif(alert.alerts_kind == 2) %>
					<td><%= "CONTINUOUSLY FAILURE" %></td>
				<% elsif(alert.alerts_kind == 3) %>
					<td><%= "TIME VARIANCE" %></td>
				<% else %>
					<td><%= "DIFF ATE VARIANCE" %></td>
				<% end %>

				<td><%= "#{alert.created_at}" %></td>
				<% if(alert.fixed == false)%>
					<td><%= "NO" %></td>
					<td><%= "N/A" %></td>
				<% else %>
					<td><%= "YES" %></td>
					<td><%= "#{alert.updated_at}" %></td>
				<% end %>
				<td><%= link_to "Detail", alert_path(alert)%></td>

			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/alerts/show.html.erb
<div class="page-header">
	<h1>Alerts <small><%= @alert.lot.name %></small></h1>
</div>

<div>
	<table class="table table-condensed table-bordered">
		<thead>
		<tr>
			<th>Lot</th>
			<th>Device</th>
			<th>Alert Type</th>
		</tr>
		</thead>
		<tbody>
		<tr class="success">
			<td><%= @alert.lot.name %></td>
			<td><%= @alert.lot.device.name %></td>
			<% case (@alert.alerts_kind) %>
			<% when 1 %>
				<td>SITE DIFFERENCE</td>
			<% when 2 %>
				<td>CONTINUOUSLY FAILURE</td>
			<% when 3 %>
				<td>TIME VARIANCE</td>
			<% else %>
				<td>DIFFERENT ATE VARIANCE</td>
			<% end %>

		</tr>
		</tbody>
	</table>
</div>

<% case (@alert.alerts_kind) %>
	<% when 1 %>
		<div>
			<table class="table table-condensed table-bordered">
				<thead>
					<tr>
						<th>Max Site</th>
						<th>Max Yield</th>
						<th>Min Site</th>
						<th>Min Yield</th>
					</tr>
				</thead>
				<tbody>
					<tr class="success">
						<td><%= @alert.max_element %></td>
						<td><%= @alert.max_yield %></td>
						<td><%= @alert.min_element %></td>
						<td><%= @alert.min_yield %></td>
					</tr>
				</tbody>
			</table>
		</div>

		<div>
			<table class="table table-condensed table-bordered">
				<thead>
				<tr>
					<th>Yield Gap</th>
					<th>Detect Threshold</th>
				</tr>
				</thead>
				<tbody>
				<tr class="success">
					<td><%= @alert.max_yield - @alert.min_yield %></td>
					<td><%= @alert.lot.device.site_difference_detect_threshold %></td>
				</tr>
				</tbody>
			</table>
		</div>
	<% when 2 %>
	<div>
		<table class="table table-condensed table-bordered">
			<thead>
			<tr>
				<th>Serial</th>
				<th>Fail Bin</th>
				<th>Continuous Fail Count(pcs)</th>
				<th>Threshold(pcs)</th>
			</tr>
			</thead>
			<tbody>
			<tr class="success">
				<td><%= @alert.detected_serial %></td>
				<td><%= @alert.continuously_fail_bin %></td>
				<td><%= @alert.continuously_fail_number %></td>
				<td><%= @alert.lot.device.continuously_failure_detect_threshold %></td>
			</tr>
			</tbody>
		</table>
	</div>
	<% when 3 %>
		<div>
			<table class="table table-condensed table-bordered">
				<thead>
				<tr>
					<th>Region 1 Size</th>
					<th>Region 1 Yield</th>
					<th>Region 2 Size</th>
					<th>Region 2 Yield</th>
				</tr>
				</thead>
				<tbody>
				<tr class="success">
					<td><%= @alert.lot.device.time_variance_detect_window_large %></td>
					<td><%= @alert.region_1_yield %></td>
					<td><%= @alert.lot.device.time_variance_detect_window_small %></td>
					<td><%= @alert.region_2_yield %></td>
				</tr>
				</tbody>
			</table>
		</div>

		<div>
			<table class="table table-condensed table-bordered">
				<thead>
				<tr>
					<th>Yield Gap</th>
					<th>Detect Threshold</th>
				</tr>
				</thead>
				<tbody>
				<tr class="success">
					<td><%= (@alert.region_1_yield - @alert.region_2_yield).abs %></td>
					<td><%= @alert.lot.device.time_variance_detect_threshold %></td>
				</tr>
				</tbody>
			</table>
		</div>
	<% else %>
	<div>
		<table class="table table-condensed table-bordered">
			<thead>
			<tr>
				<th>Max ATE</th>
				<th>Max Yield</th>
				<th>Min ATE</th>
				<th>Min Yield</th>
			</tr>
			</thead>
			<tbody>
			<tr class="success">
				<td><%= @alert.max_element %></td>
				<td><%= @alert.max_yield %></td>
				<td><%= @alert.min_element %></td>
				<td><%= @alert.min_yield %></td>
			</tr>
			</tbody>
		</table>
	</div>

	<div>
		<table class="table table-condensed table-bordered">
			<thead>
			<tr>
				<th>Yield Gap</th>
				<th>Detect Threshold</th>
			</tr>
			</thead>
			<tbody>
			<tr class="success">
				<td><%= @alert.max_yield - @alert.min_yield %></td>
				<td><%= @alert.lot.device.different_tester_variance_detect_threshold %></td>
			</tr>
			</tbody>
		</table>
	</div>
	<% end %>

<div><%= button_to 'Fix this Alert', alert_path(@alert), :method => :delete %></div>

<p><%= link_to 'Back to index', :controller=>'alerts', :action=>'index' %></p>