config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :devices
  resources :lots
  resources :sites
  resources :alerts

  root to:'root#home'
  match ':controller(/:id(/:action(.:format)))', :via => :all

end

app/models/lot.rb
class Lot < ActiveRecord::Base
  belongs_to :device
  has_many :sites, :dependent => :destroy
  has_many :data, :dependent => :destroy

  has_many :alerts

  accepts_nested_attributes_for :sites

  #validate the unique
  #validates :name, uniqueness: true

  #validate the necessary blank
  validates :name, presence: true
  validates :tester, presence: true
  validates :device, presence: true
  validates :total_device_count, presence: true
  validates :site_number, presence: true
  validates :generate_mode, presence: true

  validate :total_number_is_divisible_to_site_number

  #validate the necessary if the generate mode is NORMAL
  #validates :basic_yield, presence: true, :unless => lambda { self.generate_mode != NORMAL }

  #validates :basic_yield, presence: true, :if => :mode_normal?
  #validates :cliff_number, :first_region_yield, :second_region_yield, presence: true, :if => :mode_cliff?


  def total_number_is_divisible_to_site_number
    if((total_device_count % site_number) != 0)
      errors.add(:total_device_count, "total device count is not divisible by the site number!")
    end
  end

  

  def mode_normal?
    generate_mode == 1
  end

  def mode_cliff?
    generate_mode == 2
  end

  def mode_site_difference?
    generate_mode == 3
  end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  before_action :set_lot,  :only => [ :show,
                                     :edit_normal_params,
                                     :update_normal_params,
                                     :edit_cliff_params,
                                     :update_cliff_params,
                                     :edit_site_difference_params,
                                     :update_site_difference_params,
                                     :destroy
                                  ]
  before_action :authenticate_user!,  only: [
                                        :new,
                                        :edit_normal_params,
                                        :update_normal_params,
                                        :edit_cliff_params,
                                        :update_cliff_params,
                                        :edit_site_difference_params,
                                        :update_site_difference_params,
                                        :destroy
                                            ]


  def index
    @lots = Lot.page(params[:page]).per(10).order('id DESC')
  end

  def new
    @lot = Lot.new
    @page_title = "new lot"
  end

  def create
    @lot = Lot.new(lot_params)
    if @lot.save
      #create the rows in site table
      for i in 0..(@lot.site_number-1) do
        @lot.sites.create( :site_serial => i )
      end

      if(@lot.generate_mode == 1)
        redirect_to :action => :edit_normal_params, :id => @lot
      elsif(@lot.generate_mode == 2)
        redirect_to :action => :edit_cliff_params, :id => @lot
      else
        redirect_to :action => :edit_site_difference_params, :id => @lot
      end
    else
      render :action => :new
    end
  end

  def edit_normal_params
    @page_title = "edit " + @lot.name
  end

  def update_normal_params
    if @lot.update(lot_params)
      redirect_to :controller => :lots, :action => :index
      flash[:notice] = "lot #{@lot.name} were succesfully created"
    else
      render :action => :edit_normal_params
    end
  end

  def edit_cliff_params
    @page_title = "edit " + @lot.name
  end

  def update_cliff_params
    if @lot.update(lot_params)
      redirect_to :controller => :lots, :action => :index
      flash[:notice] = "lot #{@lot.name} were succesfully created"
    else
      render :action => :edit_cliff_params
    end
  end

  def edit_site_difference_params
    @page_title = "edit " + @lot.name
  end

  def update_site_difference_params
    if @lot.update_attributes(lot_params)
      redirect_to :action => :index
    else
      render :action => :edit_site_difference_params
    end
  end

  def show
    @sites = Site.where( :lot_id => @lot )
    @page_title = @lot.name
  end

  def destroy
    #@lot = Lot.find(params[:id])
    @lot.destroy
    flash[:alert] = "lot were succesfully deleted"

    redirect_to :action => :index
  end

  private

  def lot_params
    params.require(:lot).permit(
      :name,
      :device_id,
      :tester,
      #:device,
      :total_device_count,
      :site_number,
      :generate_mode,
      :basic_yield,
      :cliff_number,
      :first_region_yield,
      :second_region_yield,
      sites_attributes: [ :lot_id, :site_serial, :site_enable, :site_yield, :id ]
    )
  end

  def set_lot
    @lot = Lot.find(params[:id])
  end

end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/edit_cliff_params.html.erb
	<div class="page-header">
		<h1>Cliff Mode Rules <small><%= @lot.name %></small></h1>
	</div>

	<% i = 0 %>
	<%= form_for @lot, :url => { :controller => 'lots', :action => 'update_cliff_params' } do |f| %>
	<div><h4>Cliff Generation Parameters</h4></div>
	<ul>
		<li><%= f.label "Cliff:" %>
			<%= f.number_field :cliff_number, :class => 'text_field', min: 0, max: @lot.total_device_count, step: 1 %></li>
		<li><%= f.label "First Region Yield:" %>
			<%= f.number_field :first_region_yield, :class => 'text_field', min: 0.0, max: 100.0, step: 0.01 %></li>
		<li><%= f.label "Second Region Yield:" %>
			<%= f.number_field :second_region_yield, :class => 'text_field', min: 0.0, max: 100.0, step: 0.01 %></li>
	</ul>
	<%= f.fields_for :sites do |ss| %>
		<%= ss.label :site_enable do %>
			<%= ss.check_box :site_enable %>
			Site <%= i %> Enable

			<% i = i+1 %>
		<% end %>
		<br>
	<% end %>

	<br>
	<%= f.submit "Submit" %>
	<%= link_to 'back to lot index', :controller => 'lots', :action => 'index' %>

<% end %>

app/views/lots/edit_normal_params.html.erb
	<div class="page-header">
		<h1>Normal Mode Rules <small><%= @lot.name %></small></h1>
	</div>
	<% i = 0 %>
	<%= form_for @lot, :url => { :controller => 'lots', :action => 'update_normal_params' } do |f| %>
	<div><h4>Normal Generation Parameters</h4></div>
	<ul>
		<li><%= f.label "Yield:" %>
			<%= f.number_field :basic_yield, :class => 'text_field', min: 0.0, max: 100.0, step: 0.01 %></li>

		<%= f.fields_for :sites do |ss| %>
			<%= ss.label :site_enable do %>
				<%= ss.check_box :site_enable %>
				Site <%= i %> Enable

				<% i = i+1 %>
			<% end %>
			<br>
		<% end %>
	</ul>

	<br>
	<%= f.submit "Submit" %>
	<%= link_to 'back to lot index', :controller => 'lots', :action => 'index' %>

<% end %>

app/views/lots/edit_site_difference_params.html.erb
<div class="page-header">
	<h1>Site Difference Mode Rules <small><%= @lot.name %></small></h1>
</div>

<% i = 0 %>
<%= form_for @lot, :url => { :controller => 'lots', :action => 'update_site_difference_params' } do |f| %>
	<%= f.fields_for :sites do |ss| %>
		<%= ss.label :site_enable do %>
			<%= ss.check_box :site_enable %>
			Site <%= i %> Enable, Yield
			<%= ss.number_field :site_yield, :class => 'text_field', min: 0.0, max: 100.0, step: 0.01%>
			<% i = i+1 %>
		<% end %>
		<br>
	<% end %>
	<%= f.submit "submit" %>
<% end %>

app/views/lots/index.html.erb
<h1>Lots Index</h1>

<%= paginate @lots %>
<ul class="list-group">
	<% @lots.each do |lot| %>
		<li class="list-group-item">
			<%= lot.name %>
			<%= link_to("Show", lot_path(lot), class: "btn btn-default btn-xs") %>
			<%= link_to("Delete", lot_path(lot), class: "btn btn-default btn-xs", data: {confirm: "Are you sure?"}) %>
		</li>
	<% end %>
</ul>
<%= link_to 'New Lot', :controller => 'lots', :action => 'new' %>

app/views/lots/new.html.erb
<%= form_for @lot, :url => lots_path, :html => { :method => :post } do |f| %>

	<div class="page-header">
		<h1>Lot Parameter <small>New</small></h1>
	</div>

	<div><h4>Basic Parameters</h4></div>
	<ul>
		<li><%= f.label "Lot Name:" %>	<%= f.text_field :name %><br></li>
		<li><%= f.label "Tester Name:" %>	<%= f.text_field :tester %><br></li>

		<li><%= f.label "Device Name:" %>	<%= f.collection_select :device_id, Device.all, :id, :name %><br></li>
		<li><%= f.label "Total Device Count:" %>
			<%= f.number_field :total_device_count, min: 0, step: 1 %></li>
		<li><%= f.label "Site Number:" %>
			<%= f.number_field :site_number, min: 0, max: 100, step: 1 %></li>
		<li><%= f.label "Generate Mode:" %>
			<%= f.select :generate_mode, [['Normal', 1], ['Cliff', 2], ['Site Difference', 3]] %></li>
	</ul>


	<% if @lot.errors.any? %>
		<ul>
			<% @lot.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<br>
	<%= f.submit "Next" %>
	<%= link_to 'back to lot index', :controller => 'lots', :action => 'index' %>

<% end %>

app/views/lots/show.html.erb
<div class="page-header">
	<h1>Lot Parameters <small><%= @lot.name %></small></h1>
</div>

<div>
	<h4>Basic Parameters</h4>
	<ul>
		<li>Lot Name: <%= @lot.name %></li>
		<li>Tester Name: <%= @lot.tester %></li>
		<li>Device Name: <%= @lot.device.name %></li>
		<li>Total Device Count: <%= @lot.total_device_count %></li>
		<li>Site Number: <%= @lot.site_number %></li>
		<li>Generate Mode:
			<% if(@lot.generate_mode == 1) %>	Normal
			<% elsif(@lot.generate_mode == 2) %>	Cliff
			<% else %>	Site Difference
			<% end %>
		</li>
	</ul>
</div>


<% if(@lot.generate_mode == 1) %>
	<h4>Normal Generation Parameter</h4>
	<ul>
		<li>Generate Yield:  <%= @lot.basic_yield %>%</li>
	</ul>
<% elsif(@lot.generate_mode == 2) %>
	<h4>Cliff Generation Parameter</h4>
	<ul>
		<li>Cliff number:	<%= @lot.cliff_number %></li>
		<li>First region yield:	<%= @lot.first_region_yield %>%</li>
		<li>Second region yield:	<%= @lot.second_region_yield %>%</li>
	</ul>
<% else %>
	<h4>Site Difference Generation Parameter</h4>
<% end %>

<ul>
	<% for @site in @sites do %>
		<% if(@site.site_enable == true) %>
			<li>Site <%= @site.site_serial %>:	Active,
			<% if(@lot.generate_mode==1) %>
					generate yield: <%= @lot.basic_yield %>%</li>
			<% elsif(@lot.generate_mode==2) %>
			<% else %>
					generate yield: <%= @site.site_yield %>%</li>
			<% end %>
		<% else %>
			<li>Site <%= @site.site_serial %>:	Not Active.</li>
		<% end %>
	<% end %>
</ul>


<p><%= link_to 'Back to index', :controller => 'lots', :action => 'index' %></p>